-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.usuario
(
    codigo integer NOT NULL,
    apellidos character varying(255),
    cedula character varying(13),
    mail character varying(255),
    nombres character varying(255),
    direccion character varying(255),
    estado_usu integer,
    estado_vacunacion integer,
    fecha_nacimiento timestamp without time zone,
    fecha_vacunacion timestamp without time zone,
    num_dosis integer,
    pass character varying(255),
    "teléfono" character varying(255),
    tipo_usu integer,
    vacunafk integer,
    PRIMARY KEY (codigo)
);

CREATE TABLE public.vacuna
(
    codigo_vacuna integer NOT NULL,
    nombre_vacuna character varying(255),
    PRIMARY KEY (codigo_vacuna)
);

ALTER TABLE public.usuario
    ADD FOREIGN KEY (vacunafk)
    REFERENCES public.vacuna (codigo_vacuna)
    NOT VALID;

END;